#!/usr/bin/expect -f

#ssh-keygen
#Generating public/private rsa key pair.
#
#Enter file in which to save the key (/home/vsm/.ssh/id_rsa): Created directory '/home/vsm/.ssh'.
#Enter passphrase (empty for no passphrase):
#Enter same passphrase again:
#Your identification has been saved in /home/vsm/.ssh/id_rsa.
#Your public key has been saved in /home/vsm/.ssh/id_rsa.pub.
#The key fingerprint is:
#8b:46:e3:34:32:71:1f:af:76:a5:ef:86:8f:19:d2:5b vsm@jiyou-ceph-deploy-a
#The key's randomart image is:

spawn ssh-keygen

expect "Enter file in which to save the key*"
send "\r"

expect "Enter passphrase (empty for no passphrase):"
send "\r"

expect "Enter same passphrase again:"
send "\r"

expect eof
